# Default values for Go projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/silicon-synapse-254003/btcd-kube
  tag: 0.0.6
  pullPolicy: IfNotPresent
service:
  name: btcd-kube
  type: LoadBalancer
#  externalPort: 18556
  externalPort: 18334
#  internalPort: 18556
  internalPort: 18334

  http:
    externalPort: 18555
    internalPort: 18555
  rpc:
    externalPort: 18556
    internalPort: 18556

  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
#    cpu: 500m - These are values used to download entire blockchain
    cpu: 100m
#    memory: 2560Mi
    memory: 1024Mi
  requests:
#    cpu: 500m
    cpu: 100m
#    memory: 2560Mi
    memory: 1024Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
project:    #TODO: Should clean this up. Remove redundancy of network & networkSuffix
  namespace: lightning-kube-simnet
  network: simnet
  networkSuffix: -simnet
  storage: 25Gi